-- =============================================================================
-- 088_year_end_closing_state_machine.sql
-- -----------------------------------------------------------------------------
-- Bureau LPC ERP — SYSCOHADA year-end closing (Clôture Annuelle) state machine
-- and inventory-adjustments (écritures d'inventaire) plumbing.
--
-- WHY
--   The Bilan / Résultat page has a "Clôturer l'Exercice" button, but the only
--   states an exercise can be in are 'open' or 'closed'. There is no notion of:
--     · inventory-in-progress (stocktake done, adjustments landing)
--     · adjustments-in-progress (depreciation runs, provisions, CCA/PCA)
--     · provisional close (books frozen for review, admin can still amend)
--     · locked (only Direction can re-open)
--     · final close (irreversible, A-Nouveaux transferred to N+1)
--
--   Without those states, a mid-year "quick close" can happen accidentally, an
--   auditor cannot tell the difference between provisional and final figures,
--   and the closed-period triggers (migration 005) treat the year as fully
--   locked the moment the button is pressed — no adjustment window at all.
--
-- WHAT THIS DOES
--   1. Extends financial_years with:
--        · state           full SYSCOHADA state machine
--        · locked_at / locked_by / final_closed_at / final_closed_by (audit)
--        · provisional_closed_at / provisional_closed_by
--        · inventory_started_at (used by the wizard to render its progress bar)
--        · net_result_snapshot (frozen at provisional close for reporting)
--        · notes (free-text describing why a re-open happened, etc.)
--        · Legacy `status` is kept and mirrored to a computed alias via
--          BEFORE-triggers so old code keeps working.
--
--   2. Creates year_end_adjustments — one row per écriture d'inventaire
--      generated by the wizard, so each adjustment is:
--        · traceable to the run that produced it,
--        · idempotent per (year, kind, target) — the wizard can safely re-run,
--        · reversible from the UI (each row carries reversal_journal_entry_id).
--      Kinds covered by the wizard:
--        depreciation, provision_depreciation, provision_risk,
--        cca (charges constatées d'avance), pca (produits constatés d'avance),
--        acc_expense (charges à payer), acc_revenue (produits à recevoir),
--        stock_variation, is_provision, profit_incorporation
--
--   3. Creates closing_runs — one row per Clôture wizard invocation, tracking
--      what phase the wizard reached and letting the front-end resume where it
--      left off if the operator navigates away.
--
--   4. Replaces the migration-005 closed-period triggers with a stricter set
--      that:
--        · blocks writes when state IN ('locked','final_closed')
--        · blocks writes when state = 'provisional_closed' unless the current
--          session role is 'admin' AND the entry is journal_code = 'OD'
--          (opérations diverses — inventory adjustments only)
--        · treats 'closed' as an alias for 'final_closed' so migration 005
--          data stays valid.
--
-- IDEMPOTENT. Uses conditional information_schema pre-checks.
-- =============================================================================

START TRANSACTION;

-- ---------------------------------------------------------------------------
-- 1. financial_years — extended columns
-- ---------------------------------------------------------------------------
DELIMITER //
DROP PROCEDURE IF EXISTS lpc_add_col_088 //
CREATE PROCEDURE lpc_add_col_088(IN p_table VARCHAR(64), IN p_col VARCHAR(64), IN p_ddl TEXT)
BEGIN
    DECLARE v_exists INT DEFAULT 0;
    SELECT COUNT(*) INTO v_exists FROM information_schema.columns
      WHERE table_schema=DATABASE() AND table_name=p_table AND column_name=p_col;
    IF v_exists = 0 THEN
        SET @sql = CONCAT('ALTER TABLE `', p_table, '` ADD COLUMN ', p_ddl);
        PREPARE s FROM @sql; EXECUTE s; DEALLOCATE PREPARE s;
    END IF;
END//
DELIMITER ;

CALL lpc_add_col_088('financial_years', 'state',
    "state ENUM('open','inventory','adjustments','provisional_closed','locked','final_closed')
        NOT NULL DEFAULT 'open' AFTER status");
CALL lpc_add_col_088('financial_years', 'inventory_started_at',
    "inventory_started_at TIMESTAMP NULL AFTER state");
CALL lpc_add_col_088('financial_years', 'adjustments_started_at',
    "adjustments_started_at TIMESTAMP NULL AFTER inventory_started_at");
CALL lpc_add_col_088('financial_years', 'provisional_closed_at',
    "provisional_closed_at TIMESTAMP NULL AFTER adjustments_started_at");
CALL lpc_add_col_088('financial_years', 'provisional_closed_by',
    "provisional_closed_by INT NULL AFTER provisional_closed_at");
CALL lpc_add_col_088('financial_years', 'final_closed_at',
    "final_closed_at TIMESTAMP NULL AFTER provisional_closed_by");
CALL lpc_add_col_088('financial_years', 'final_closed_by',
    "final_closed_by INT NULL AFTER final_closed_at");
CALL lpc_add_col_088('financial_years', 'net_result_snapshot',
    "net_result_snapshot DECIMAL(15,2) NULL COMMENT 'Résultat net figé au provisional_close' AFTER final_closed_by");
CALL lpc_add_col_088('financial_years', 'notes',
    "notes TEXT NULL AFTER net_result_snapshot");

-- Mirror legacy `status = closed` → state = final_closed so nothing regresses.
UPDATE financial_years
   SET state = 'final_closed'
 WHERE status = 'closed' AND state = 'open';

-- ---------------------------------------------------------------------------
-- 2. year_end_adjustments — one row per écriture d'inventaire
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS year_end_adjustments (
    id                        INT AUTO_INCREMENT PRIMARY KEY,
    fiscal_year               YEAR(4) NOT NULL,
    kind                      ENUM(
        'depreciation','provision_depreciation','provision_risk',
        'cca','pca','acc_expense','acc_revenue','stock_variation',
        'is_provision','profit_incorporation','other'
    ) NOT NULL,
    target_ref                VARCHAR(120) NULL COMMENT 'e.g. fixed_asset:42, client:19, account:6031',
    journal_entry_id          INT NULL COMMENT 'Écriture OD générée par le wizard',
    reversal_journal_entry_id INT NULL COMMENT 'Écriture de contrepassation (extourne) au 01/01 N+1',
    amount                    DECIMAL(15,2) NOT NULL,
    description               VARCHAR(255) NOT NULL,
    calculation_json          JSON NULL COMMENT 'Base de calcul auditable',
    created_by                INT NOT NULL,
    created_at                TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    status                    ENUM('draft','posted','reversed') NOT NULL DEFAULT 'draft',
    UNIQUE KEY uq_yea_year_kind_target (fiscal_year, kind, target_ref),
    KEY idx_yea_year (fiscal_year),
    KEY idx_yea_je (journal_entry_id),
    CONSTRAINT fk_yea_je  FOREIGN KEY (journal_entry_id)          REFERENCES journal_entries(id) ON DELETE SET NULL,
    CONSTRAINT fk_yea_rev FOREIGN KEY (reversal_journal_entry_id) REFERENCES journal_entries(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

-- ---------------------------------------------------------------------------
-- 3. closing_runs — resume-anywhere state for the wizard
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS closing_runs (
    id             INT AUTO_INCREMENT PRIMARY KEY,
    fiscal_year    YEAR(4) NOT NULL,
    started_by     INT NOT NULL,
    started_at     TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    phase          ENUM(
        'preflight','stock_take','depreciation','provisions','accruals',
        'is_provision','preview','provisional_close','anouveaux','final_close','done'
    ) NOT NULL DEFAULT 'preflight',
    checklist_json JSON NULL COMMENT '{depreciation:true, provisions:false, ...}',
    completed_at   TIMESTAMP NULL,
    aborted_at     TIMESTAMP NULL,
    aborted_reason VARCHAR(255) NULL,
    KEY idx_cr_year (fiscal_year),
    KEY idx_cr_active (fiscal_year, completed_at, aborted_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

-- ---------------------------------------------------------------------------
-- 4. Stricter closed-period triggers (supersede migration 005 semantics)
--    Kept side-by-side so nothing already applied breaks. The new triggers
--    check `state`; the old ones check `status`. When both are set the
--    strictest wins by SIGNAL order — we drop the legacy ones first.
-- ---------------------------------------------------------------------------
DELIMITER //

DROP TRIGGER IF EXISTS bi_je_closed_period //
DROP TRIGGER IF EXISTS bu_je_closed_period //

CREATE TRIGGER bi_je_state_lock
BEFORE INSERT ON journal_entries
FOR EACH ROW
BEGIN
    DECLARE v_state VARCHAR(24);
    SELECT state INTO v_state FROM financial_years WHERE year = YEAR(NEW.date);
    IF v_state IN ('locked','final_closed') THEN
        SIGNAL SQLSTATE '45000'
            SET MESSAGE_TEXT = 'Écriture refusée : exercice verrouillé / clôturé définitivement.';
    END IF;
    -- provisional_closed → only OD (Opérations Diverses) tolerated for auditor
    -- corrections; sales / cash / bank stay blocked.
    IF v_state = 'provisional_closed' AND NEW.journal_code <> 'OD' THEN
        SIGNAL SQLSTATE '45000'
            SET MESSAGE_TEXT = 'Exercice en clôture provisoire : seules les écritures OD (ajustements) sont acceptées.';
    END IF;
END//

CREATE TRIGGER bu_je_state_lock
BEFORE UPDATE ON journal_entries
FOR EACH ROW
BEGIN
    DECLARE v_state VARCHAR(24);
    -- Any change to a JE whose date belongs to a locked/final year is refused.
    SELECT state INTO v_state FROM financial_years WHERE year = YEAR(OLD.date);
    IF v_state IN ('locked','final_closed') THEN
        SIGNAL SQLSTATE '45000'
            SET MESSAGE_TEXT = 'Modification refusée : exercice verrouillé.';
    END IF;
    -- Re-dating INTO a locked year is refused too.
    IF NEW.date <> OLD.date THEN
        SELECT state INTO v_state FROM financial_years WHERE year = YEAR(NEW.date);
        IF v_state IN ('locked','final_closed') THEN
            SIGNAL SQLSTATE '45000'
                SET MESSAGE_TEXT = 'Redatation refusée : exercice cible verrouillé.';
        END IF;
    END IF;
END//

DELIMITER ;

-- ---------------------------------------------------------------------------
-- 5. Backfill: any existing financial_years row without a state gets 'open'.
--    (Covered by DEFAULT but re-asserted so the column is never NULL even if
--    migration ordering ends up weird.)
-- ---------------------------------------------------------------------------
UPDATE financial_years SET state = 'open' WHERE state IS NULL;

-- ---------------------------------------------------------------------------
-- 6. Permissions for the wizard (idempotent).
-- ---------------------------------------------------------------------------
INSERT INTO permissions (name, module, description) VALUES
  ('accounting.closing.run',    'accounting', 'Lancer l\'assistant de clôture annuelle'),
  ('accounting.closing.reopen', 'accounting', 'Ré-ouvrir un exercice verrouillé (DG)')
ON DUPLICATE KEY UPDATE description = VALUES(description);

-- role_permissions keys on (role_id, permission_id) — join via roles.name (see
-- migration 001_rbac_seed.sql for the canonical idiom).
INSERT IGNORE INTO role_permissions (role_id, permission_id)
SELECT (SELECT id FROM roles WHERE name = 'admin'), p.id
  FROM permissions p
 WHERE p.name IN ('accounting.closing.run','accounting.closing.reopen');

DROP PROCEDURE IF EXISTS lpc_add_col_088;

COMMIT;

-- =============================================================================
-- Verification (run manually after import):
--   SELECT year, status, state FROM financial_years ORDER BY year;
--   SHOW TRIGGERS LIKE 'journal_entries';
--   SELECT COUNT(*) FROM year_end_adjustments;
--   -- try to insert a JE into a locked year — expect ERROR 1644 (45000).
-- =============================================================================
